language: node_js
node_js:
  - 0.10
notifications:
  irc:
    nick: gulp-slm
    channels:
      - irc.example.com:16667#redacted
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
after_script:
  - mocha --require blanket -R mocha-lcov-reporter | coveralls
